# Generated by Django 4.1 on 2024-06-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='polls/default-avatar.png', upload_to='polls/'),
        ),
    ]
