# Generated by Django 4.1 on 2024-06-06 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only Alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only Alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8, 'Password must be at least 8 characters long.'), django.core.validators.RegexValidator('^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*\\W).*$', 'Password should contain atleast one uppercase, one lowercase, one digit and one special character.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinValueValidator(3, 'Username must be at least 3 characters long.'), django.core.validators.RegexValidator('^[^\\W_](\\w)*$', 'Username should not start with a special character.')]),
        ),
    ]
