# Generated by Django 4.1 on 2024-06-06 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Username must be at least 3 characters long.'), django.core.validators.RegexValidator('^[^\\W_](\\w)*$', 'Username should not start with a special character.')]),
        ),
    ]
