# Generated by Django 4.1 on 2024-06-15 11:38

from django.conf import settings
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='viewed_blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
