# Generated by Django 4.1 on 2024-06-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('polls', '0014_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='groups.group'),
        ),
    ]
